KVERSION=4.15.0-74-generic
CONFIG_COMPAT_VERSION=
CONFIG_COMPAT_KOBJECT_BACKPORT=
BACKPORT_INCLUDES=
ARCH=x86_64

CFLAGS_RETPOLINE=

MODULES_DIR:=/lib/modules/4.15.0-74-generic/updates
KSRC=/lib/modules/4.15.0-74-generic/build
KSRC_OBJ=/lib/modules/4.15.0-74-generic/build
KLIB_BUILD=/lib/modules/4.15.0-74-generic/build
CWD=/home/obe/mlx5/scripts
MLNX_EN_EXTRA_CFLAGS:=
CONFIG_MEMTRACK:=
CONFIG_MLX4_EN_DCB:=y
CONFIG_MLX4_CORE:=m
CONFIG_MLX4_CORE_GEN2:=y
CONFIG_MLX4_EN:=m
CONFIG_MLX5_CORE:=m
CONFIG_MLX5_CORE_EN:=y
CONFIG_MLX5_CORE_EN_DCB:=y
CONFIG_MLX5_EN_ARFS:=y
CONFIG_MLX5_EN_RXNFC:=y
CONFIG_MLX5_ESWITCH:=y
CONFIG_MLX5_MPFS:=y
CONFIG_MLXFW:=m
CONFIG_MLNX_BLOCK_REQUEST_MODULE:=
